# Generated by Django 4.2.1 on 2023-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_sent/'),
        ),
    ]
