# Generated by Django 4.2.1 on 2023-06-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_offer_discription_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.offer'),
        ),
    ]
