# Generated by Django 4.2.1 on 2023-07-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
